import { useState } from 'react';

const order = ['planner-agent', 'research-agent', 'graph-builder-agent', 'writer-agent', 'evaluation-agent'];
const roles = { 'planner-agent': 'PLANNER', 'research-agent': 'RESEARCH', 'graph-builder-agent': 'GRAPH', 'writer-agent': 'WRITER', 'evaluation-agent': 'EVALUATION' };
const descriptions = { 'planner-agent': 'Generated research topics', 'research-agent': 'Collected evidence and context', 'graph-builder-agent': 'Extracted entities and relationships', 'writer-agent': 'Generated the research report', 'evaluation-agent': 'Quality evaluation completed' };

export default function AgentExecutionTrace({ research }) {
  const traces = Array.isArray(research.traces) ? research.traces : [];
  const results = Array.isArray(research.agentResults) ? research.agentResults : [];
  const [open, setOpen] = useState(null);
  const agents = [...traces].sort((a, b) => (order.indexOf(a.agentId) + 99) - (order.indexOf(b.agentId) + 99));
  if (!agents.length) return <div className="grid min-h-56 place-items-center border border-dashed border-white/10 p-8 text-center"><p className="text-sm text-slate-500">Agent execution data is unavailable for this run.</p></div>;
  const color = (status) => ({ COMPLETED: 'text-emerald-300', FAILED: 'text-rose-300', RUNNING: 'text-cyan-200', QUEUED: 'text-amber-300', PENDING: 'text-slate-400' }[status] || 'text-slate-500');
  return <div className="space-y-3"><div className="mb-6 flex items-end justify-between"><div><p className="eyebrow mb-2">Execution trace</p><h2 className="text-lg font-semibold text-white">Recorded agent activity</h2></div><span className="font-mono text-xs text-slate-600">{agents.length} traces</span></div>{agents.map((trace, index) => { const result = results[index]; const isOpen = open === trace.traceId; return <article key={trace.traceId || `${trace.agentId}-${index}`} className="border border-white/10 bg-[#0b111b]"><button type="button" aria-expanded={isOpen} onClick={() => setOpen(isOpen ? null : trace.traceId)} className="flex w-full items-center gap-4 p-4 text-left transition hover:bg-white/[0.025] sm:p-5"><span className={`grid h-8 w-8 shrink-0 place-items-center border border-white/10 font-mono text-sm ${color(trace.status)}`}>{trace.status === 'COMPLETED' ? '✓' : trace.status === 'FAILED' ? '!' : '·'}</span><span className="min-w-0 flex-1"><span className="block text-sm font-medium text-white">{trace.agentName || trace.agentId}</span><span className="mt-1 block text-xs text-slate-600">{roles[trace.agentId] || 'AGENT'} · step {trace.executionOrder ?? '—'}</span></span><span className="hidden text-right sm:block"><span className={`block font-mono text-[10px] uppercase ${color(trace.status)}`}>{trace.status || 'UNAVAILABLE'}</span><span className="mt-1 block font-mono text-[10px] text-slate-600">{trace.durationMs ? `${(trace.durationMs / 1000).toFixed(1)}s` : 'duration unavailable'}</span></span><span className="text-slate-600">{isOpen ? '−' : '+'}</span></button>{isOpen && <div className="border-t border-white/10 px-5 pb-5 pl-16"><p className="pt-4 text-sm text-slate-400">{descriptions[trace.agentId] || 'No output summary was returned.'}</p>{trace.error && <div className="mt-4 border border-rose-400/20 bg-rose-400/5 p-3 text-xs text-rose-200">{trace.error.message || String(trace.error)}</div>}{result && <pre className="mt-4 max-h-48 overflow-auto border border-white/10 bg-[#080b12] p-3 font-mono text-[10px] leading-5 text-slate-500">{JSON.stringify(result, null, 2)}</pre>}</div>}</article>; })}<div className="grid gap-3 border-t border-white/10 pt-5 sm:grid-cols-4">{[['Completed', agents.filter((item) => item.status === 'COMPLETED').length, 'text-emerald-300'], ['Failed', agents.filter((item) => item.status === 'FAILED').length, 'text-rose-300'], ['Recorded', agents.length, 'text-white'], ['Duration', research.summary?.totalDurationMs ? `${Math.round(research.summary.totalDurationMs / 1000)}s` : '—', 'text-cyan-200']].map(([label, value, tone]) => <div key={label}><p className="font-mono text-[10px] uppercase tracking-widest text-slate-600">{label}</p><p className={`mt-2 text-xl font-semibold ${tone}`}>{value}</p></div>)}</div></div>;
}
